export const ACCOUNT_STATUS = {
   ACTIVE: 1,
   INACTIVE: 2,
   SUSPENDED: 3,
   PENDING: 4,
};

export const LIST_STATUS = [
   ACCOUNT_STATUS.ACTIVE,
   ACCOUNT_STATUS.INACTIVE,
   ACCOUNT_STATUS.SUSPENDED,
   ACCOUNT_STATUS.PENDING,
];

export const INACTIVE_STATUSES = [ACCOUNT_STATUS.INACTIVE, ACCOUNT_STATUS.SUSPENDED];

export const STATUS_DESCRIPTIONS = {
   [ACCOUNT_STATUS.ACTIVE]: 'Active',
   [ACCOUNT_STATUS.INACTIVE]: 'Inactive',
   [ACCOUNT_STATUS.SUSPENDED]: 'Suspended',
   [ACCOUNT_STATUS.PENDING]: 'Pending',
};
